/**
 * Service detail page content — full 8-language i18n.
 */

import { Lang } from './i18n';

type L<T> = Record<Lang, T>;

export interface ServiceDetail {
  slug: string;
  icon: string;
  image: string;
  price: string;
  name: L<string>;
  italic: L<string>;
  duration: L<string>;
  description: L<string>;
  benefits: L<string[]>;
  process: L<{ step: string; detail: string }[]>;
  aftercare: L<string[]>;
  faq: L<{ q: string; a: string }[]>;
}

export const SERVICE_DETAILS: ServiceDetail[] = [
  {
    slug: 'microblading',
    icon: '✿',
    image: '/client-3.jpg',
    price: '3.500.000đ+',
    name: {
      VI: 'Microblading', EN: 'Microblading', RU: 'Микроблейдинг', ZH: '雾眉',
      JA: 'マイクロブレーディング', KO: '마이크로블레이딩', FR: 'Microblading', ES: 'Microblading',
    },
    italic: {
      VI: 'Chân Mày', EN: 'Brows', RU: 'Брови', ZH: '眉毛',
      JA: '眉', KO: '눈썹', FR: 'Sourcils', ES: 'Cejas',
    },
    duration: {
      VI: '2-3 giờ', EN: '2-3 hours', RU: '2-3 часа', ZH: '2-3 小时',
      JA: '2〜3時間', KO: '2-3시간', FR: '2-3 heures', ES: '2-3 horas',
    },
    description: {
      VI: 'Kỹ thuật vẽ từng sợi lông mày bằng dao 3D mảnh, tạo chân mày tự nhiên đến mức không phát hiện được là đã phun xăm. Phù hợp cho người có lông mày thưa, không đối xứng, hoặc muốn nâng tầm khuôn mặt.',
      EN: 'Hair-stroke technique using a fine 3D blade, creating brows so natural that no one can tell they were tattooed. Ideal for sparse, asymmetric brows, or to elevate facial features.',
      RU: 'Техника прорисовки каждого волоска тонким 3D-лезвием. Брови выглядят настолько естественно, что невозможно понять, что это татуаж. Подходит для редких, асимметричных бровей или для подчёркивания черт лица.',
      ZH: '使用精细 3D 刀片逐根勾勒眉丝，眉毛自然到无人能察觉是纹绣。适合眉毛稀疏、不对称或希望提升五官的人。',
      JA: '繊細な 3D ブレードで一本一本眉毛を描く技術。タトゥーとは気づかれないほど自然な眉に。薄い・左右非対称な眉、または顔立ちを引き立てたい方に最適。',
      KO: '미세한 3D 블레이드로 한 올 한 올 그리는 기법. 누구도 시술 사실을 알아차리지 못할 만큼 자연스러운 눈썹. 숱이 적거나 비대칭, 또는 얼굴을 돋보이게 하고 싶은 분에게 이상적.',
      FR: "Technique poil par poil avec une fine lame 3D, donnant des sourcils si naturels qu'on ne devine pas le tatouage. Idéal pour les sourcils clairsemés, asymétriques ou pour valoriser les traits.",
      ES: 'Técnica pelo a pelo con una fina cuchilla 3D, creando cejas tan naturales que nadie nota que están tatuadas. Ideal para cejas escasas, asimétricas o para realzar los rasgos.',
    },
    benefits: {
      VI: ['Tự nhiên đến từng sợi lông', 'Bền màu 2-3 năm', 'Phù hợp mọi cấu trúc khuôn mặt', 'Không cần kẻ mày mỗi ngày', 'Mực organic an toàn'],
      EN: ['Hair-stroke realism', '2–3 year longevity', 'Suits every facial structure', 'No daily brow makeup needed', 'Safe organic pigment'],
      RU: ['Реализм волосок к волоску', 'Стойкость 2–3 года', 'Подходит под любое лицо', 'Не нужно красить брови ежедневно', 'Безопасный органический пигмент'],
      ZH: ['一根根逼真', '持久 2-3 年', '适合所有脸型', '无需每天画眉', '有机色乳安全'],
      JA: ['一本一本リアル', '2〜3年持続', 'どんな顔立ちにも合う', '毎日眉を描く必要なし', '安全なオーガニック色素'],
      KO: ['한 올 한 올 사실적', '2-3년 지속', '모든 얼굴형에 적합', '매일 눈썹 그릴 필요 없음', '안전한 유기농 색소'],
      FR: ['Réalisme poil par poil', 'Tenue 2 à 3 ans', "S'adapte à tous les visages", "Pas besoin de maquiller les sourcils", 'Pigment organique sûr'],
      ES: ['Realismo pelo a pelo', '2-3 años de duración', 'Se adapta a cualquier rostro', 'Sin necesidad de maquillar cejas', 'Pigmento orgánico seguro'],
    },
    process: {
      VI: [
        { step: 'Tư vấn 1-1', detail: 'Phân tích khuôn mặt, dáng mày phù hợp, chọn màu mực.' },
        { step: 'Vẽ phom thử', detail: 'Vẽ phom mày bằng bút mỹ phẩm, chị xem ưng mới làm.' },
        { step: 'Ủ tê', detail: 'Ủ tê 30 phút để giảm cảm giác khó chịu khi phun.' },
        { step: 'Microblading', detail: 'Đi từng nét lông mảnh bằng dao 3D, mất 1-2 giờ.' },
        { step: 'Hoàn thiện', detail: 'Vệ sinh, dưỡng da, hướng dẫn chăm sóc 7 ngày.' },
      ],
      EN: [
        { step: '1-on-1 consultation', detail: 'Face analysis, choose brow shape, pick the pigment color.' },
        { step: 'Sketch preview', detail: 'Drawing the shape with cosmetic pencil — only proceed when you love it.' },
        { step: 'Numbing', detail: '30-minute numbing to minimize discomfort.' },
        { step: 'Microblading', detail: 'Hand-tooled 3D-blade strokes, 1–2 hours.' },
        { step: 'Finish', detail: 'Cleansing, balm, 7-day aftercare guide.' },
      ],
      RU: [
        { step: 'Консультация 1:1', detail: 'Анализ лица, выбор формы бровей, подбор пигмента.' },
        { step: 'Эскиз', detail: 'Прорисовка карандашом — приступаем только после вашего одобрения.' },
        { step: 'Обезболивание', detail: '30 минут анестезии для минимизации дискомфорта.' },
        { step: 'Микроблейдинг', detail: 'Прорисовка волосков 3D-лезвием, 1-2 часа.' },
        { step: 'Завершение', detail: 'Очищение, бальзам, инструкция по уходу на 7 дней.' },
      ],
      ZH: [
        { step: '一对一咨询', detail: '面部分析、选择眉形、确定色乳颜色。' },
        { step: '预绘草图', detail: '用化妆笔预绘 — 您满意后才进行。' },
        { step: '麻醉', detail: '30 分钟敷麻以减少不适。' },
        { step: '雾眉绣', detail: '使用 3D 刀片手工勾勒，1-2 小时。' },
        { step: '完成', detail: '清洁、护肤膏、7 天护理指南。' },
      ],
      JA: [
        { step: '1対1カウンセリング', detail: '顔分析、眉形の選択、色素の選定。' },
        { step: 'スケッチプレビュー', detail: '化粧ペンで下書き — 気に入ってから施術。' },
        { step: '麻酔', detail: '30 分間の表面麻酔で不快感を最小限に。' },
        { step: 'マイクロブレーディング', detail: '3D ブレードで手仕事、1〜2 時間。' },
        { step: '仕上げ', detail: '洗浄、バーム、7 日間のアフターケア説明。' },
      ],
      KO: [
        { step: '1:1 상담', detail: '얼굴 분석, 눈썹 모양 선택, 색소 선정.' },
        { step: '스케치 프리뷰', detail: '화장 펜으로 그림 — 마음에 들 때만 진행.' },
        { step: '마취', detail: '30분 마취로 불편함 최소화.' },
        { step: '마이크로블레이딩', detail: '3D 블레이드 수작업, 1-2시간.' },
        { step: '마무리', detail: '세정, 밤, 7일 사후 관리 가이드.' },
      ],
      FR: [
        { step: 'Consultation 1:1', detail: 'Analyse du visage, choix de la forme et du pigment.' },
        { step: 'Esquisse', detail: 'Dessin au crayon cosmétique — on avance seulement si vous adorez.' },
        { step: 'Anesthésie', detail: '30 minutes pour minimiser l\'inconfort.' },
        { step: 'Microblading', detail: 'Traits à la lame 3D, 1-2 heures.' },
        { step: 'Finition', detail: 'Nettoyage, baume, guide d\'après-soin de 7 jours.' },
      ],
      ES: [
        { step: 'Consulta 1:1', detail: 'Análisis facial, elección de forma y color.' },
        { step: 'Boceto', detail: 'Dibujo a lápiz — solo seguimos si te encanta.' },
        { step: 'Anestesia', detail: '30 minutos para minimizar la incomodidad.' },
        { step: 'Microblading', detail: 'Trazos a cuchilla 3D, 1-2 horas.' },
        { step: 'Acabado', detail: 'Limpieza, bálsamo, guía de cuidado de 7 días.' },
      ],
    },
    aftercare: {
      VI: ['Kiêng nước 24h đầu', 'Không trang điểm vùng mày 7 ngày', 'Không phơi nắng trực tiếp', 'Bôi dưỡng theo hướng dẫn', 'Tái khám sau 1 tháng (miễn phí dặm lại)'],
      EN: ['Avoid water for the first 24h', 'No makeup on the brow area for 7 days', 'No direct sun exposure', 'Apply the provided balm as instructed', '1-month touch-up visit (free)'],
      RU: ['Избегайте воды первые 24 часа', 'Никакого макияжа на бровях 7 дней', 'Без прямого солнца', 'Используйте бальзам по инструкции', 'Контрольный визит через месяц (бесплатно)'],
      ZH: ['前 24 小时避水', '眉部 7 天内不化妆', '避免阳光直射', '按说明使用护肤膏', '1 个月后复诊（免费补色）'],
      JA: ['最初の 24 時間は水を避ける', '7 日間眉メイク禁止', '直射日光を避ける', '指示通りバームを塗る', '1 ヶ月後のリタッチ（無料）'],
      KO: ['첫 24시간 물 피하기', '7일간 눈썹 화장 금지', '직사광선 피하기', '안내에 따라 밤 도포', '1개월 후 리터치 방문 (무료)'],
      FR: ["Évitez l'eau les 24 premières heures", 'Pas de maquillage sur les sourcils 7 jours', 'Pas de soleil direct', 'Appliquez le baume comme indiqué', 'Retouche à 1 mois (gratuite)'],
      ES: ['Evita el agua las primeras 24h', 'Sin maquillaje en cejas 7 días', 'Sin sol directo', 'Aplica el bálsamo según indicado', 'Retoque al mes (gratis)'],
    },
    faq: {
      VI: [
        { q: 'Có đau không?', a: 'Đã ủ tê nên chỉ hơi tê nhẹ như kiến cắn.' },
        { q: 'Bao lâu thì lành?', a: '7-10 ngày bong nhẹ, 1 tháng lên màu chuẩn.' },
        { q: 'Bảo hành như thế nào?', a: 'Dặm lại miễn phí 1 năm sau khi làm.' },
      ],
      EN: [
        { q: 'Does it hurt?', a: 'With numbing applied it feels like a mild ant bite.' },
        { q: 'How long is healing?', a: 'Light peeling for 7–10 days, full color at 1 month.' },
        { q: 'Is there a warranty?', a: 'Free touch-up within 1 year of the procedure.' },
      ],
      RU: [
        { q: 'Это больно?', a: 'С анестезией ощущения как лёгкий укус муравья.' },
        { q: 'Сколько заживает?', a: 'Лёгкое шелушение 7–10 дней, полный цвет через 1 месяц.' },
        { q: 'Есть ли гарантия?', a: 'Бесплатная коррекция в течение 1 года после процедуры.' },
      ],
      ZH: [
        { q: '会痛吗？', a: '敷麻后感觉像被蚂蚁轻咬。' },
        { q: '多久能愈合？', a: '7-10 天轻微脱皮，1 个月后呈现真实颜色。' },
        { q: '有保修吗？', a: '术后 1 年内免费补色。' },
      ],
      JA: [
        { q: '痛みはありますか？', a: '麻酔後は軽い蟻に刺された程度の感覚です。' },
        { q: '治癒期間は？', a: '7〜10 日間軽く剥け、1 ヶ月で本来の色に。' },
        { q: '保証はありますか？', a: '施術後 1 年以内のリタッチ無料。' },
      ],
      KO: [
        { q: '아픈가요?', a: '마취 후에는 개미에게 살짝 물린 느낌입니다.' },
        { q: '치유 기간은?', a: '7-10일간 가볍게 벗겨지며, 1개월 후 본래 색상으로.' },
        { q: '보증이 있나요?', a: '시술 후 1년 이내 무료 리터치.' },
      ],
      FR: [
        { q: 'Est-ce douloureux ?', a: "Avec l'anesthésie, c'est comme une légère piqûre de fourmi." },
        { q: 'Combien de temps pour cicatriser ?', a: 'Légère desquamation 7-10 jours, couleur définitive à 1 mois.' },
        { q: 'Y a-t-il une garantie ?', a: "Retouche gratuite dans l'année suivant la procédure." },
      ],
      ES: [
        { q: '¿Duele?', a: 'Con anestesia se siente como una leve picadura de hormiga.' },
        { q: '¿Cuánto tarda en sanar?', a: 'Descamación leve 7-10 días, color definitivo al mes.' },
        { q: '¿Hay garantía?', a: 'Retoque gratis dentro de 1 año tras el procedimiento.' },
      ],
    },
  },
  {
    slug: 'lip-blush',
    icon: '♡',
    image: '/PMU-lip.jpg',
    price: '3.000.000đ+',
    name: { VI: 'Lip Blush', EN: 'Lip Blush', RU: 'Татуаж губ', ZH: '唇釉纹绣', JA: 'リップブラッシュ', KO: '립 블러쉬', FR: 'Lip Blush', ES: 'Lip Blush' },
    italic: { VI: 'Phun Môi', EN: 'PMU Lips', RU: 'PMU губы', ZH: '唇部 PMU', JA: 'PMU リップ', KO: 'PMU 입술', FR: 'PMU Lèvres', ES: 'PMU Labios' },
    duration: { VI: '1.5-2 giờ', EN: '1.5-2 hours', RU: '1.5-2 часа', ZH: '1.5-2 小时', JA: '1.5〜2 時間', KO: '1.5-2시간', FR: '1.5-2 heures', ES: '1.5-2 horas' },
    description: {
      VI: 'Phun lót màu môi tạo đôi môi căng mọng tự nhiên màu hồng đất / cherry / berry tùy chọn. Hiệu ứng như vừa cắn quả mọng, không bị "đậm" như xăm môi truyền thống.',
      EN: 'A soft pigment layer for plump, natural-looking lips in earth pink / cherry / berry. The effect of "just bitten a berry", never as bold as old-school lip tattoos.',
      RU: 'Мягкий слой пигмента для пухлых натуральных губ в оттенках землистой розы / вишни / ягоды. Эффект "только что укусили ягоду", без жёсткости старых татуажей.',
      ZH: '柔和的色乳为唇部带来饱满自然的色彩 — 大地玫瑰 / 樱桃 / 莓果。"刚咬过浆果"的效果，不像传统纹唇那样浓重。',
      JA: 'ふっくら自然なリップを叶える、アースピンク / チェリー / ベリーの柔らかな色素層。「ベリーを噛んだばかり」のような効果で、従来のリップタトゥーのような重さはありません。',
      KO: '도톰하고 자연스러운 입술을 위한 부드러운 색소 — 어스 핑크 / 체리 / 베리. 전통적인 입술 문신처럼 진하지 않은 "베리를 막 베어 문" 효과.',
      FR: "Un voile pigmentaire doux pour des lèvres pulpeuses et naturelles, ton terre rose / cerise / baie. Effet 'juste mordu une baie', loin des tatouages traditionnels.",
      ES: 'Una capa suave de pigmento para labios voluminosos y naturales en rosa tierra / cereza / baya. Efecto "recién mordí una baya", nunca tan fuerte como los tatuajes tradicionales.',
    },
    benefits: {
      VI: ['Màu môi tự nhiên, không bị "phun"', 'Đa dạng tone: hồng đất, cherry, berry', 'Bền màu 2-3 năm', 'Che được sẹo, đường viền môi mờ', 'Hợp với mọi tone da'],
      EN: ['Natural lip color, never "tattooed" looking', 'Variety of tones: earth pink, cherry, berry', '2–3 year longevity', 'Covers scars and faded lip lines', 'Suits every skin tone'],
      RU: ['Натуральный цвет, без эффекта татуажа', 'Разные оттенки: земля, вишня, ягода', 'Стойкость 2–3 года', 'Скрывает шрамы и размытый контур', 'Подходит любому тону кожи'],
      ZH: ['自然唇色，无"纹绣"痕迹', '多种色调：大地玫瑰、樱桃、莓果', '持久 2-3 年', '掩盖疤痕和模糊唇线', '适合所有肤色'],
      JA: ['自然な唇色、タトゥー感なし', '多彩な色調：アースピンク、チェリー、ベリー', '2〜3 年持続', '傷跡や薄れたリップラインを隠す', 'すべての肌色に合う'],
      KO: ['자연스러운 입술 색, "문신" 느낌 없음', '다양한 톤: 어스 핑크, 체리, 베리', '2-3년 지속', '흉터와 흐려진 입술선 커버', '모든 피부톤에 적합'],
      FR: ["Couleur naturelle, jamais d'effet 'tatoué'", 'Variété de tons : rose terre, cerise, baie', 'Tenue 2 à 3 ans', 'Couvre cicatrices et contour estompé', "Convient à tous les tons de peau"],
      ES: ['Color natural, nunca "tatuado"', 'Variedad de tonos: rosa tierra, cereza, baya', '2-3 años de duración', 'Cubre cicatrices y contornos difuminados', 'Apto para todo tono de piel'],
    },
    process: {
      VI: [
        { step: 'Tư vấn màu', detail: 'Chọn tone phù hợp với tone da, dáng môi.' },
        { step: 'Test patch', detail: 'Thử mực trên cổ tay 30 phút để chắc không dị ứng.' },
        { step: 'Ủ tê', detail: 'Ủ tê môi 30 phút.' },
        { step: 'Phun lót màu', detail: 'Đi mực đều theo từng lớp, 1-1.5 giờ.' },
        { step: 'Dưỡng + hướng dẫn', detail: 'Vệ sinh, bôi dưỡng, hướng dẫn 7 ngày.' },
      ],
      EN: [
        { step: 'Shade consultation', detail: 'Choose the right tone for your skin and lip shape.' },
        { step: 'Patch test', detail: 'Pigment test on the wrist for 30 minutes — allergy safety.' },
        { step: 'Numbing', detail: '30-minute lip numbing.' },
        { step: 'Pigment layering', detail: 'Even, layered pigment passes — 1 to 1.5 hours.' },
        { step: 'Balm + guide', detail: 'Cleansing, balm, 7-day aftercare guide.' },
      ],
      RU: [
        { step: 'Консультация по цвету', detail: 'Подбор тона под кожу и форму губ.' },
        { step: 'Тест на аллергию', detail: 'Проба на запястье 30 минут.' },
        { step: 'Обезболивание', detail: '30 минут анестезии губ.' },
        { step: 'Послойное нанесение', detail: 'Равномерные слои пигмента — 1-1.5 часа.' },
        { step: 'Бальзам + инструкция', detail: 'Очищение, бальзам, инструкция на 7 дней.' },
      ],
      ZH: [
        { step: '色彩咨询', detail: '根据肤色和唇形选择合适色调。' },
        { step: '过敏测试', detail: '在手腕上测试色乳 30 分钟。' },
        { step: '麻醉', detail: '30 分钟唇部麻醉。' },
        { step: '层层上色', detail: '均匀分层上色，1-1.5 小时。' },
        { step: '护理指南', detail: '清洁、护肤膏、7 天护理说明。' },
      ],
      JA: [
        { step: '色のカウンセリング', detail: '肌色と唇の形に合わせた色調選び。' },
        { step: 'パッチテスト', detail: '手首で 30 分のアレルギーテスト。' },
        { step: '麻酔', detail: '30 分の唇麻酔。' },
        { step: '色素の重ね塗り', detail: '均一に重ねる色素、1〜1.5 時間。' },
        { step: 'バーム + ガイド', detail: '洗浄、バーム、7 日間のアフターケア。' },
      ],
      KO: [
        { step: '색상 상담', detail: '피부톤과 입술 모양에 맞는 톤 선택.' },
        { step: '패치 테스트', detail: '손목에 30분 색소 테스트.' },
        { step: '마취', detail: '30분 입술 마취.' },
        { step: '색소 레이어링', detail: '균일한 색소 레이어, 1-1.5시간.' },
        { step: '밤 + 가이드', detail: '세정, 밤, 7일 사후 관리 가이드.' },
      ],
      FR: [
        { step: 'Choix de la teinte', detail: 'Ton adapté à la peau et à la forme des lèvres.' },
        { step: 'Test cutané', detail: '30 minutes de test sur le poignet.' },
        { step: 'Anesthésie', detail: '30 minutes pour les lèvres.' },
        { step: 'Couches pigmentaires', detail: 'Couches uniformes — 1 à 1,5 heure.' },
        { step: 'Baume + guide', detail: 'Nettoyage, baume, guide de 7 jours.' },
      ],
      ES: [
        { step: 'Consulta de tono', detail: 'Tono adecuado para tu piel y forma de labios.' },
        { step: 'Prueba alérgica', detail: '30 minutos en la muñeca.' },
        { step: 'Anestesia', detail: '30 minutos en los labios.' },
        { step: 'Capas de pigmento', detail: 'Capas uniformes — 1 a 1,5 horas.' },
        { step: 'Bálsamo + guía', detail: 'Limpieza, bálsamo, guía de 7 días.' },
      ],
    },
    aftercare: {
      VI: ['Kiêng đồ cay nóng 5 ngày', 'Uống nhiều nước, dưỡng môi liên tục', 'Không liếm/cắn môi', 'Không phơi nắng', 'Tái khám 1 tháng (dặm lại miễn phí)'],
      EN: ['Avoid spicy/hot food for 5 days', 'Drink plenty of water, keep lips balmed', 'No licking or biting your lips', 'No sun exposure', '1-month touch-up visit (free)'],
      RU: ['Избегайте острого/горячего 5 дней', 'Пейте много воды, увлажняйте губы', 'Не облизывайте и не кусайте', 'Без солнца', 'Контроль через месяц (бесплатно)'],
      ZH: ['5 天内禁辛辣热食', '多喝水，持续唇部保湿', '不要舔/咬嘴唇', '避免阳光', '1 个月后复诊（免费补色）'],
      JA: ['5 日間辛い・熱い食べ物を避ける', '水分補給、リップ保湿', '舐めたり噛んだりしない', '日光を避ける', '1 ヶ月後のリタッチ（無料）'],
      KO: ['5일간 매운/뜨거운 음식 피하기', '수분 섭취, 립 보습 유지', '입술 핥기/물기 금지', '햇빛 피하기', '1개월 후 리터치 (무료)'],
      FR: ['Évitez épices/chaud pendant 5 jours', "Buvez beaucoup d'eau, baume en continu", 'Ne pas lécher/mordre les lèvres', 'Pas de soleil', 'Retouche à 1 mois (gratuite)'],
      ES: ['Evita comida picante/caliente 5 días', 'Bebe mucha agua, mantén labios hidratados', 'No te lamas/muerdas los labios', 'Sin sol', 'Retoque al mes (gratis)'],
    },
    faq: {
      VI: [
        { q: 'Có đau không?', a: 'Ít hơn xăm chân mày vì môi đã ủ tê kỹ.' },
        { q: 'Lên màu ngay không?', a: '7-10 ngày sau mới ổn định, đẹp tự nhiên.' },
        { q: 'Có mất màu không?', a: 'Mất từ từ trong 2-3 năm, dặm lại để bền.' },
      ],
      EN: [
        { q: 'Does it hurt?', a: 'Less than brows because the lips are well numbed.' },
        { q: 'Does color show right away?', a: 'It stabilizes 7–10 days later, then heals beautifully.' },
        { q: 'Does it fade?', a: 'It fades gradually over 2–3 years; touch-ups extend it.' },
      ],
      RU: [
        { q: 'Это больно?', a: 'Меньше чем брови — губы хорошо обезболены.' },
        { q: 'Цвет проявится сразу?', a: 'Стабилизируется через 7-10 дней.' },
        { q: 'Цвет выцветает?', a: 'Постепенно за 2-3 года; коррекция продлевает.' },
      ],
      ZH: [
        { q: '会痛吗？', a: '比眉毛还轻，唇部麻醉到位。' },
        { q: '会立即上色吗？', a: '7-10 天后稳定，自然漂亮。' },
        { q: '会褪色吗？', a: '2-3 年逐渐褪色；补色可延长。' },
      ],
      JA: [
        { q: '痛みは？', a: '眉より軽い、唇麻酔がしっかり効きます。' },
        { q: 'すぐ色が出る？', a: '7〜10 日で落ち着き、自然な仕上がりに。' },
        { q: '色は薄くなる？', a: '2〜3 年で徐々に。リタッチで持続。' },
      ],
      KO: [
        { q: '아픈가요?', a: '눈썹보다 덜 아픕니다, 입술 마취가 잘 됩니다.' },
        { q: '바로 색이 보이나요?', a: '7-10일 후 안정되어 자연스럽게.' },
        { q: '색이 빠지나요?', a: '2-3년에 걸쳐 서서히; 리터치로 연장.' },
      ],
      FR: [
        { q: 'Est-ce douloureux ?', a: 'Moins que les sourcils, lèvres bien anesthésiées.' },
        { q: 'Couleur immédiate ?', a: 'Stabilise après 7-10 jours, magnifique cicatrisation.' },
        { q: 'Ça s\'estompe ?', a: 'Estompe sur 2-3 ans ; les retouches prolongent.' },
      ],
      ES: [
        { q: '¿Duele?', a: 'Menos que cejas, labios bien anestesiados.' },
        { q: '¿Color inmediato?', a: 'Se estabiliza en 7-10 días, sana hermoso.' },
        { q: '¿Se desvanece?', a: 'Gradualmente en 2-3 años; los retoques lo extienden.' },
      ],
    },
  },
  {
    slug: 'eyeliner',
    icon: '★',
    image: '/client-2.jpg',
    price: '2.500.000đ+',
    name: { VI: 'Eyeliner', EN: 'Eyeliner', RU: 'Стрелки', ZH: '美瞳线', JA: 'アイライン', KO: '아이라이너', FR: 'Eyeliner', ES: 'Delineador' },
    italic: { VI: 'PMU', EN: 'PMU', RU: 'PMU', ZH: 'PMU', JA: 'PMU', KO: 'PMU', FR: 'PMU', ES: 'PMU' },
    duration: { VI: '1-1.5 giờ', EN: '1-1.5 hours', RU: '1-1.5 часа', ZH: '1-1.5 小时', JA: '1〜1.5 時間', KO: '1-1.5시간', FR: '1-1.5 heures', ES: '1-1.5 horas' },
    description: {
      VI: 'Phun đường kẻ mắt mảnh tinh tế bằng kỹ thuật PMU hiện đại. Đôi mắt lúc nào cũng có hồn, không cần kẻ mỗi ngày. Phù hợp với phụ nữ bận rộn.',
      EN: 'A refined eyeliner line via modern PMU. Captivating eyes 24/7 without daily makeup. Perfect for busy women.',
      RU: 'Утончённая стрелка с современным PMU. Выразительные глаза 24/7 без ежедневного макияжа. Идеально для занятых женщин.',
      ZH: '采用现代 PMU 技术绘制精致眼线。24/7 迷人双眼，无需每天化妆。适合忙碌的女性。',
      JA: '現代の PMU による洗練されたアイライン。毎日のメイクなしで 24/7 魅惑的な瞳に。忙しい女性に最適。',
      KO: '현대 PMU 기법으로 세련된 아이라인. 매일 화장 없이도 24/7 매혹적인 눈. 바쁜 여성에게 완벽.',
      FR: 'Un trait fin et élégant grâce au PMU moderne. Des yeux captivants 24/7 sans maquillage quotidien. Parfait pour les femmes actives.',
      ES: 'Una línea fina y elegante con PMU moderno. Ojos cautivadores 24/7 sin maquillaje diario. Perfecto para mujeres ocupadas.',
    },
    benefits: {
      VI: ['Mắt có hồn 24/7', 'Tiết kiệm thời gian trang điểm', 'Bền 2-3 năm', 'An toàn vùng mắt', 'Tinh tế, không "dại"'],
      EN: ['Captivating eyes 24/7', 'Saves makeup time', '2–3 year longevity', 'Safe for the eye area', 'Refined, never harsh'],
      RU: ['Выразительные глаза 24/7', 'Экономия времени на макияж', '2–3 года стойкости', 'Безопасно для глаз', 'Утончённо, никогда не грубо'],
      ZH: ['24/7 迷人双眸', '节省化妆时间', '持久 2-3 年', '眼部安全', '精致不生硬'],
      JA: ['24/7 魅惑の瞳', 'メイク時間短縮', '2〜3 年持続', '目元に安全', '洗練、決して硬くない'],
      KO: ['24/7 매혹적인 눈', '화장 시간 절약', '2-3년 지속', '눈가에 안전', '세련되고 자연스러움'],
      FR: ['Yeux captivants 24/7', "Gagne du temps de maquillage", 'Tenue 2-3 ans', 'Sûr pour les yeux', 'Raffiné, jamais dur'],
      ES: ['Ojos cautivadores 24/7', 'Ahorra tiempo de maquillaje', '2-3 años de duración', 'Seguro para los ojos', 'Refinado, nunca duro'],
    },
    process: {
      VI: [
        { step: 'Tư vấn', detail: 'Chọn dáng kẻ phù hợp dáng mắt.' },
        { step: 'Vẽ thử', detail: 'Vẽ thử bằng eyeliner, chị xem ưng mới phun.' },
        { step: 'Ủ tê', detail: 'Ủ tê chuyên dụng cho vùng mắt.' },
        { step: 'Phun', detail: 'Đi từng nét mảnh, 30-45 phút.' },
        { step: 'Hoàn thiện', detail: 'Vệ sinh, hướng dẫn chăm sóc.' },
      ],
      EN: [
        { step: 'Consultation', detail: 'Pick the right line shape for your eye type.' },
        { step: 'Sketch preview', detail: 'Drawn with eyeliner pencil — only proceed when you approve.' },
        { step: 'Numbing', detail: 'Specialized numbing for the eye area.' },
        { step: 'Application', detail: 'Fine line application, 30–45 minutes.' },
        { step: 'Finish', detail: 'Cleansing and aftercare guidance.' },
      ],
      RU: [
        { step: 'Консультация', detail: 'Подбираем форму стрелки под ваши глаза.' },
        { step: 'Эскиз', detail: 'Карандашом — приступаем только после одобрения.' },
        { step: 'Анестезия', detail: 'Специальная анестезия для век.' },
        { step: 'Нанесение', detail: 'Тонкая линия, 30-45 минут.' },
        { step: 'Завершение', detail: 'Очищение и инструкции.' },
      ],
      ZH: [
        { step: '咨询', detail: '根据眼型选择眼线形状。' },
        { step: '试画', detail: '用眼线笔预画 — 满意后才进行。' },
        { step: '麻醉', detail: '眼部专用麻醉。' },
        { step: '上线', detail: '细线绘制，30-45 分钟。' },
        { step: '完成', detail: '清洁和护理说明。' },
      ],
      JA: [
        { step: 'カウンセリング', detail: '目の形に合うライン形を選ぶ。' },
        { step: 'スケッチ', detail: 'アイライナーで下書き — OK 後施術。' },
        { step: '麻酔', detail: '目元専用麻酔。' },
        { step: '施術', detail: '細いライン、30〜45 分。' },
        { step: '仕上げ', detail: '洗浄とアフターケア説明。' },
      ],
      KO: [
        { step: '상담', detail: '눈 모양에 맞는 라인 선택.' },
        { step: '스케치', detail: '아이라이너로 그림 — 승인 후 진행.' },
        { step: '마취', detail: '눈가 전용 마취.' },
        { step: '시술', detail: '얇은 라인, 30-45분.' },
        { step: '마무리', detail: '세정과 사후 관리 안내.' },
      ],
      FR: [
        { step: 'Consultation', detail: 'Choix du trait selon votre œil.' },
        { step: 'Esquisse', detail: 'Au crayon — accord avant de poursuivre.' },
        { step: 'Anesthésie', detail: 'Spécifique à la zone des yeux.' },
        { step: 'Application', detail: 'Trait fin, 30-45 minutes.' },
        { step: 'Finition', detail: 'Nettoyage et conseils.' },
      ],
      ES: [
        { step: 'Consulta', detail: 'Forma del trazo según tu ojo.' },
        { step: 'Boceto', detail: 'A lápiz — solo seguimos con tu aprobación.' },
        { step: 'Anestesia', detail: 'Específica para la zona de los ojos.' },
        { step: 'Aplicación', detail: 'Trazo fino, 30-45 minutos.' },
        { step: 'Acabado', detail: 'Limpieza e instrucciones.' },
      ],
    },
    aftercare: {
      VI: ['Không dụi mắt 7 ngày', 'Không trang điểm mắt 5 ngày', 'Không tắm hồ bơi 1 tuần', 'Bôi dưỡng theo hướng dẫn'],
      EN: ['Do not rub eyes for 7 days', 'No eye makeup for 5 days', 'No swimming pool for 1 week', 'Apply balm as instructed'],
      RU: ['Не трите глаза 7 дней', 'Без макияжа глаз 5 дней', 'Без бассейна 1 неделю', 'Бальзам по инструкции'],
      ZH: ['7 天内不揉眼', '5 天内不化眼妆', '1 周内不游泳', '按说明使用护肤膏'],
      JA: ['7 日間目をこすらない', '5 日間アイメイク禁止', '1 週間プール禁止', '指示通りバーム使用'],
      KO: ['7일간 눈 비비지 않기', '5일간 눈 화장 금지', '1주간 수영장 금지', '안내에 따라 밤 사용'],
      FR: ['Pas de frottement des yeux 7 jours', "Pas de maquillage des yeux 5 jours", 'Pas de piscine 1 semaine', 'Baume comme indiqué'],
      ES: ['No frotar los ojos 7 días', 'Sin maquillaje de ojos 5 días', 'Sin piscina 1 semana', 'Bálsamo según indicado'],
    },
    faq: {
      VI: [{ q: 'Có an toàn không?', a: 'Tuyệt đối an toàn nếu thực hiện đúng kỹ thuật.' }, { q: 'Có sưng không?', a: 'Hơi sưng nhẹ 1-2 ngày đầu, rồi xẹp lại.' }],
      EN: [{ q: 'Is it safe?', a: 'Absolutely safe with correct technique.' }, { q: 'Will it swell?', a: 'Mild swelling for 1–2 days, then it subsides.' }],
      RU: [{ q: 'Это безопасно?', a: 'Абсолютно безопасно при правильной технике.' }, { q: 'Будет ли отёк?', a: 'Лёгкий отёк 1-2 дня, затем спадает.' }],
      ZH: [{ q: '安全吗？', a: '正确技术下绝对安全。' }, { q: '会肿吗？', a: '前 1-2 天轻微肿胀，之后消退。' }],
      JA: [{ q: '安全ですか？', a: '正しい技術なら完全に安全です。' }, { q: '腫れますか？', a: '最初の 1〜2 日軽く腫れ、その後引きます。' }],
      KO: [{ q: '안전한가요?', a: '올바른 기법이면 완전히 안전합니다.' }, { q: '붓나요?', a: '1-2일 가볍게 붓고 가라앉습니다.' }],
      FR: [{ q: 'Est-ce sûr ?', a: 'Totalement sûr avec une bonne technique.' }, { q: 'Y a-t-il un gonflement ?', a: 'Léger gonflement 1-2 jours, puis ça redescend.' }],
      ES: [{ q: '¿Es seguro?', a: 'Totalmente seguro con buena técnica.' }, { q: '¿Hay hinchazón?', a: 'Leve hinchazón 1-2 días, luego baja.' }],
    },
  },
  {
    slug: 'noi-mi',
    icon: '✦',
    image: '/noi-mi.jpg',
    price: '800.000đ+',
    name: { VI: 'Nối mi', EN: 'Lash Extensions', RU: 'Наращивание ресниц', ZH: '种睫毛', JA: 'まつげエクステ', KO: '속눈썹 연장', FR: 'Extensions de cils', ES: 'Extensiones de pestañas' },
    italic: { VI: 'Volume', EN: 'Volume', RU: 'Volume', ZH: 'Volume', JA: 'Volume', KO: 'Volume', FR: 'Volume', ES: 'Volume' },
    duration: { VI: '1.5-2 giờ', EN: '1.5-2 hours', RU: '1.5-2 часа', ZH: '1.5-2 小时', JA: '1.5〜2 時間', KO: '1.5-2시간', FR: '1.5-2 heures', ES: '1.5-2 horas' },
    description: {
      VI: 'Nối mi giả sợi vào mi thật, tạo hàng mi dày cong tự nhiên. 3 kiểu: Classic (mỏng), Volume (dày), Mega Volume (cực dày).',
      EN: 'Synthetic lashes attached to your natural lashes — full, naturally curled. 3 styles: Classic (light), Volume (full), Mega Volume (extra full).',
      RU: 'Синтетические ресницы крепятся к натуральным — густые, естественно изогнутые. 3 стиля: Classic (лёгкий), Volume (густой), Mega Volume (очень густой).',
      ZH: '将合成睫毛粘贴到天然睫毛上 — 浓密自然卷翘。3 种风格：Classic (轻盈)、Volume (浓密)、Mega Volume (超浓密)。',
      JA: '人工毛をご自身のまつげに装着 — ボリュームと自然なカール。3 スタイル：Classic、Volume、Mega Volume。',
      KO: '인조 속눈썹을 본인 속눈썹에 부착 — 풍성하고 자연스러운 컬. 3가지 스타일: Classic, Volume, Mega Volume.',
      FR: "Cils synthétiques fixés à vos cils naturels — denses, naturellement recourbés. 3 styles : Classic (léger), Volume (dense), Mega Volume (très dense).",
      ES: 'Pestañas sintéticas fijadas a las naturales — densas, naturalmente rizadas. 3 estilos: Classic (ligero), Volume (denso), Mega Volume (muy denso).',
    },
    benefits: {
      VI: ['Mi dày cong tự nhiên', 'Giữ form 4-6 tuần', 'Đi biển, tắm vẫn ổn', 'Tiết kiệm mascara'],
      EN: ['Naturally full curled lashes', 'Holds shape 4–6 weeks', 'Beach- and shower-friendly', 'Saves on mascara'],
      RU: ['Естественно густые завитые', 'Держит форму 4–6 недель', 'Подходят для пляжа и душа', 'Экономия туши'],
      ZH: ['自然浓密卷翘', '保持 4-6 周', '海滩、淋浴均可', '节省睫毛膏'],
      JA: ['自然にボリューム & カール', '4〜6 週間持続', 'ビーチやシャワー OK', 'マスカラ節約'],
      KO: ['자연스럽게 풍성한 컬', '4-6주 유지', '해변과 샤워 OK', '마스카라 절약'],
      FR: ['Cils volumineux naturellement recourbés', 'Tient 4-6 semaines', 'Compatible plage/douche', 'Économise le mascara'],
      ES: ['Pestañas naturalmente rizadas y densas', 'Dura 4-6 semanas', 'Apto playa y ducha', 'Ahorra rímel'],
    },
    process: {
      VI: [
        { step: 'Tư vấn kiểu', detail: 'Chọn Classic / Volume / Mega.' },
        { step: 'Làm sạch mi', detail: 'Vệ sinh kỹ vùng mắt.' },
        { step: 'Nối từng sợi', detail: 'Dùng kẹp chuyên dụng nối vào mi thật.' },
        { step: 'Hoàn thiện', detail: 'Chải gọn, hướng dẫn chăm sóc.' },
      ],
      EN: [
        { step: 'Style consultation', detail: 'Choose Classic / Volume / Mega.' },
        { step: 'Lash cleansing', detail: 'Thorough eye-area cleansing.' },
        { step: 'Lash-by-lash', detail: 'Specialized tweezers attach lashes individually.' },
        { step: 'Finish', detail: 'Final brushing + aftercare instructions.' },
      ],
      RU: [
        { step: 'Стиль', detail: 'Выбор Classic / Volume / Mega.' },
        { step: 'Очищение', detail: 'Тщательное очищение зоны глаз.' },
        { step: 'Поресничное наращивание', detail: 'Специальный пинцет крепит каждую ресницу.' },
        { step: 'Завершение', detail: 'Расчёсывание + инструкция.' },
      ],
      ZH: [
        { step: '风格咨询', detail: '选择 Classic / Volume / Mega。' },
        { step: '清洁睫毛', detail: '彻底清洁眼部区域。' },
        { step: '逐根嫁接', detail: '专用镊子逐根粘贴。' },
        { step: '完成', detail: '梳理 + 护理说明。' },
      ],
      JA: [
        { step: 'スタイル選び', detail: 'Classic / Volume / Mega から選択。' },
        { step: 'まつげ洗浄', detail: '目元を丁寧に洗浄。' },
        { step: '一本ずつ装着', detail: '専用ツィザーで一本ずつ。' },
        { step: '仕上げ', detail: 'ブラッシング + アフターケア。' },
      ],
      KO: [
        { step: '스타일 상담', detail: 'Classic / Volume / Mega 선택.' },
        { step: '속눈썹 세정', detail: '눈가 철저히 세정.' },
        { step: '한 올씩 부착', detail: '전용 트위저로 한 올씩.' },
        { step: '마무리', detail: '브러싱 + 사후 관리.' },
      ],
      FR: [
        { step: 'Style', detail: 'Classic / Volume / Mega.' },
        { step: 'Nettoyage', detail: 'Nettoyage approfondi des yeux.' },
        { step: 'Cil par cil', detail: 'Pince spécialisée, cil par cil.' },
        { step: 'Finition', detail: 'Brossage + entretien.' },
      ],
      ES: [
        { step: 'Estilo', detail: 'Classic / Volume / Mega.' },
        { step: 'Limpieza', detail: 'Limpieza profunda de los ojos.' },
        { step: 'Pelo a pelo', detail: 'Pinzas especiales, pelo a pelo.' },
        { step: 'Acabado', detail: 'Cepillado + cuidado.' },
      ],
    },
    aftercare: {
      VI: ['24h đầu không tiếp xúc nước', 'Không dụi mắt', 'Không bôi mascara/dầu vùng mắt', 'Chải mi mỗi sáng'],
      EN: ['No water in the first 24h', 'Do not rub eyes', 'No mascara/oil in the eye area', 'Brush lashes each morning'],
      RU: ['Без воды первые 24 часа', 'Не трите глаза', 'Без туши/масла на глазах', 'Расчёсывайте утром'],
      ZH: ['前 24 小时不接触水', '不揉眼', '眼部不用睫毛膏/油', '每天早上梳理'],
      JA: ['最初の 24 時間は水に触れない', '目をこすらない', 'マスカラ/オイル禁止', '毎朝ブラッシング'],
      KO: ['첫 24시간 물 접촉 금지', '눈 비비지 않기', '마스카라/오일 금지', '매일 아침 빗어주기'],
      FR: ["Pas d'eau les 24 premières heures", 'Pas de frottement des yeux', 'Pas de mascara/huile sur les yeux', 'Brosser chaque matin'],
      ES: ['Sin agua las primeras 24h', 'No frotar los ojos', 'Sin rímel/aceite en ojos', 'Peinar cada mañana'],
    },
    faq: {
      VI: [{ q: 'Có hại mi thật không?', a: 'Không nếu nối đúng kỹ thuật và chăm sóc đúng.' }, { q: 'Bao lâu phải dặm?', a: '3-4 tuần nên đi dặm để giữ form đẹp.' }],
      EN: [{ q: 'Will it damage my natural lashes?', a: 'No, with correct technique and proper care.' }, { q: 'How often to refill?', a: 'Every 3–4 weeks to keep the look fresh.' }],
      RU: [{ q: 'Повредит ли натуральные ресницы?', a: 'Нет, при правильной технике и уходе.' }, { q: 'Когда коррекция?', a: 'Каждые 3-4 недели.' }],
      ZH: [{ q: '会损伤天然睫毛吗？', a: '正确技术和护理下不会。' }, { q: '多久补一次？', a: '每 3-4 周补一次。' }],
      JA: [{ q: '自まつげを傷めますか？', a: '正しい技術とケアなら傷めません。' }, { q: 'リフィルは？', a: '3〜4 週間ごと。' }],
      KO: [{ q: '본 속눈썹이 상하나요?', a: '올바른 기법과 관리면 안 상합니다.' }, { q: '리필 주기는?', a: '3-4주마다.' }],
      FR: [{ q: 'Cela abîme-t-il mes cils naturels ?', a: 'Non, avec une bonne technique et un bon entretien.' }, { q: 'Tous les combien remplir ?', a: 'Toutes les 3-4 semaines.' }],
      ES: [{ q: '¿Daña mis pestañas naturales?', a: 'No, con buena técnica y cuidado.' }, { q: '¿Cada cuánto rellenar?', a: 'Cada 3-4 semanas.' }],
    },
  },
  {
    slug: 'nail-art',
    icon: '❀',
    image: '/nail.jpg',
    price: '500.000đ+',
    name: { VI: 'Nail Art', EN: 'Nail Art', RU: 'Дизайн ногтей', ZH: '美甲艺术', JA: 'ネイルアート', KO: '네일 아트', FR: 'Nail Art', ES: 'Nail Art' },
    italic: { VI: 'Độc Quyền', EN: 'Custom', RU: 'Эксклюзив', ZH: '定制', JA: 'カスタム', KO: '맞춤', FR: 'Sur-mesure', ES: 'Personalizado' },
    duration: { VI: '1-2 giờ', EN: '1-2 hours', RU: '1-2 часа', ZH: '1-2 小时', JA: '1〜2 時間', KO: '1-2시간', FR: '1-2 heures', ES: '1-2 horas' },
    description: {
      VI: 'Thiết kế nail art độc bản theo phong cách riêng. Không đụng hàng. Có thể yêu cầu sketch riêng hoặc chọn từ thư viện 100+ mẫu.',
      EN: 'Custom nail art designs in your own style. One-of-a-kind. Bring your sketch or choose from a library of 100+ patterns.',
      RU: 'Эксклюзивный дизайн ногтей в вашем стиле. Уникально. Свой эскиз или выбор из 100+ шаблонов.',
      ZH: '独家美甲设计，您专属风格。独一无二。可自带草图或从 100+ 款式中选择。',
      JA: 'あなただけのネイルアートデザイン。唯一無二。スケッチ持参 OK、100+ パターンから選択可。',
      KO: '나만의 스타일 맞춤 네일 아트. 유일무이. 스케치 지참 또는 100+ 패턴에서 선택.',
      FR: 'Designs de nail art sur-mesure dans votre style. Uniques. Apportez votre croquis ou choisissez parmi 100+ motifs.',
      ES: 'Diseños de nail art personalizados a tu estilo. Únicos. Trae tu boceto o elige de 100+ patrones.',
    },
    benefits: {
      VI: ['Mẫu độc quyền', 'Bền 2-3 tuần', 'An toàn cho móng', 'Đa dạng style'],
      EN: ['Exclusive designs', '2–3 week durability', 'Nail-safe', 'Wide style range'],
      RU: ['Эксклюзивные дизайны', '2–3 недели стойкости', 'Безопасно для ногтей', 'Широкий выбор стилей'],
      ZH: ['专属设计', '持久 2-3 周', '指甲安全', '风格多样'],
      JA: ['オリジナルデザイン', '2〜3 週間持続', '爪に安全', '多彩なスタイル'],
      KO: ['독점 디자인', '2-3주 내구성', '손톱에 안전', '다양한 스타일'],
      FR: ['Designs exclusifs', 'Durée 2-3 semaines', 'Sûr pour les ongles', 'Styles variés'],
      ES: ['Diseños exclusivos', '2-3 semanas de duración', 'Seguro para uñas', 'Estilos variados'],
    },
    process: {
      VI: [
        { step: 'Tư vấn', detail: 'Chọn mẫu hoặc sketch riêng.' },
        { step: 'Cắt sửa', detail: 'Cắt da, dũa móng đúng dáng.' },
        { step: 'Đắp nền', detail: 'Đắp gel nền chống bong.' },
        { step: 'Vẽ art', detail: 'Vẽ thiết kế đã chọn.' },
        { step: 'Hoàn thiện', detail: 'Phủ topcoat, dưỡng móng.' },
      ],
      EN: [
        { step: 'Consultation', detail: 'Pick a pattern or bring your own sketch.' },
        { step: 'Prep', detail: 'Cuticle care + filing to your preferred shape.' },
        { step: 'Base', detail: 'Anti-lift gel base layer.' },
        { step: 'Art', detail: 'Hand-painted custom design.' },
        { step: 'Finish', detail: 'Top coat + nail care.' },
      ],
      RU: [
        { step: 'Консультация', detail: 'Выбор узора или свой эскиз.' },
        { step: 'Подготовка', detail: 'Уход за кутикулой + опил.' },
        { step: 'База', detail: 'База против отслоения.' },
        { step: 'Дизайн', detail: 'Ручная роспись.' },
        { step: 'Завершение', detail: 'Топ + уход за ногтями.' },
      ],
      ZH: [
        { step: '咨询', detail: '选图案或自带草图。' },
        { step: '准备', detail: '甘皮护理 + 修甲。' },
        { step: '底胶', detail: '防起翘底胶。' },
        { step: '彩绘', detail: '手工定制设计。' },
        { step: '完成', detail: '封层 + 指甲护理。' },
      ],
      JA: [
        { step: 'カウンセリング', detail: 'パターン選択または持参 OK。' },
        { step: '準備', detail: 'キューティクルケア + 整爪。' },
        { step: 'ベース', detail: 'リフト防止ベースジェル。' },
        { step: 'アート', detail: 'ハンドペイント。' },
        { step: '仕上げ', detail: 'トップコート + ネイルケア。' },
      ],
      KO: [
        { step: '상담', detail: '패턴 선택 또는 스케치 지참.' },
        { step: '준비', detail: '큐티클 케어 + 모양 정리.' },
        { step: '베이스', detail: '리프트 방지 젤 베이스.' },
        { step: '아트', detail: '핸드 페인팅 맞춤 디자인.' },
        { step: '마무리', detail: '톱 코트 + 손톱 관리.' },
      ],
      FR: [
        { step: 'Consultation', detail: 'Motif ou votre croquis.' },
        { step: 'Préparation', detail: 'Cuticules + limage selon forme.' },
        { step: 'Base', detail: 'Base gel anti-décollement.' },
        { step: 'Art', detail: 'Design peint à la main.' },
        { step: 'Finition', detail: 'Top coat + soin des ongles.' },
      ],
      ES: [
        { step: 'Consulta', detail: 'Patrón o tu boceto.' },
        { step: 'Preparación', detail: 'Cutículas + limado de forma.' },
        { step: 'Base', detail: 'Base de gel antidespegue.' },
        { step: 'Arte', detail: 'Diseño pintado a mano.' },
        { step: 'Acabado', detail: 'Top coat + cuidado de uñas.' },
      ],
    },
    aftercare: {
      VI: ['Đeo bao tay khi rửa chén', 'Không cắn móng', 'Dưỡng cuticle hàng ngày'],
      EN: ['Wear gloves while doing dishes', 'Avoid biting your nails', 'Daily cuticle oil'],
      RU: ['Перчатки при мытье посуды', 'Не грызите ногти', 'Масло для кутикулы ежедневно'],
      ZH: ['洗碗时戴手套', '不咬指甲', '每天保养甘皮'],
      JA: ['食器洗い時は手袋着用', '爪を噛まない', '毎日キューティクルオイル'],
      KO: ['설거지 시 장갑 착용', '손톱 물어뜯지 않기', '매일 큐티클 오일'],
      FR: ['Portez des gants en faisant la vaisselle', 'Ne mordez pas vos ongles', 'Huile pour cuticules tous les jours'],
      ES: ['Usa guantes al fregar', 'No te muerdas las uñas', 'Aceite de cutículas a diario'],
    },
    faq: {
      VI: [{ q: 'Có làm móng yếu không?', a: 'Không nếu dùng gel chất lượng và tháo đúng cách.' }, { q: 'Bao lâu nên đi dặm?', a: '2-3 tuần khi móng dài ra.' }],
      EN: [{ q: 'Will it weaken my nails?', a: 'Not when using quality gel and proper removal.' }, { q: 'How often should I refill?', a: 'Every 2–3 weeks as your nails grow out.' }],
      RU: [{ q: 'Ослабит ли это ногти?', a: 'Нет при качественном геле и правильном снятии.' }, { q: 'Когда коррекция?', a: 'Каждые 2-3 недели.' }],
      ZH: [{ q: '会让指甲变薄吗？', a: '使用优质胶并正确卸除则不会。' }, { q: '多久补一次？', a: '每 2-3 周补一次。' }],
      JA: [{ q: '爪が弱くなりますか？', a: '高品質ジェルと正しいオフなら問題なし。' }, { q: 'リフィルは？', a: '2〜3 週間ごと。' }],
      KO: [{ q: '손톱이 약해지나요?', a: '양질의 젤과 올바른 제거면 괜찮습니다.' }, { q: '리필 주기는?', a: '2-3주마다.' }],
      FR: [{ q: 'Cela affaiblit-il mes ongles ?', a: 'Non avec un gel de qualité et un retrait correct.' }, { q: 'Tous les combien remplir ?', a: 'Toutes les 2-3 semaines.' }],
      ES: [{ q: '¿Debilita mis uñas?', a: 'No con buen gel y retirada correcta.' }, { q: '¿Cada cuánto rellenar?', a: 'Cada 2-3 semanas.' }],
    },
  },
  {
    slug: 'cham-soc-da',
    icon: '❁',
    image: '/cami-van.jpg',
    price: '700.000đ+',
    name: { VI: 'Chăm sóc da', EN: 'Skin Care', RU: 'Уход за кожей', ZH: '皮肤护理', JA: 'スキンケア', KO: '피부 관리', FR: 'Soin de la peau', ES: 'Cuidado de la piel' },
    italic: { VI: 'Facial', EN: 'Facial', RU: 'Facial', ZH: 'Facial', JA: 'Facial', KO: 'Facial', FR: 'Facial', ES: 'Facial' },
    duration: { VI: '60-90 phút', EN: '60-90 minutes', RU: '60-90 минут', ZH: '60-90 分钟', JA: '60〜90 分', KO: '60-90분', FR: '60-90 minutes', ES: '60-90 minutos' },
    description: {
      VI: 'Liệu trình facial cao cấp giúp da glow tự nhiên, sạch sâu, mịn màng. Bao gồm massage, mask, dưỡng phù hợp tình trạng da.',
      EN: 'Premium facial treatment for natural glow, deep cleansing, and smooth skin. Includes massage, mask, and treatment matched to your skin condition.',
      RU: 'Премиум-уход для естественного сияния, глубокого очищения и гладкой кожи. Массаж, маска и уход под состояние кожи.',
      ZH: '高级护肤疗程，自然光泽、深层清洁和光滑肌肤。包括按摩、面膜和针对肌肤状况的护理。',
      JA: '自然な輝き、深層クレンジング、なめらか肌のためのプレミアムフェイシャル。マッサージ、マスク、肌状態に合わせたケアを含む。',
      KO: '자연스러운 광채, 깊은 클렌징, 매끄러운 피부를 위한 프리미엄 페이셜. 마사지, 마스크, 피부 상태 맞춤 케어 포함.',
      FR: "Soin facial premium pour un éclat naturel, un nettoyage profond et une peau lisse. Comprend massage, masque et soin adapté à votre peau.",
      ES: 'Tratamiento facial premium para brillo natural, limpieza profunda y piel suave. Incluye masaje, mascarilla y tratamiento según tu piel.',
    },
    benefits: {
      VI: ['Da sạch sâu', 'Glow tự nhiên', 'Mịn màng', 'Phù hợp da nhạy cảm', 'Thư giãn'],
      EN: ['Deep-cleansed skin', 'Natural glow', 'Smooth texture', 'Sensitive-skin friendly', 'Relaxing'],
      RU: ['Глубокая очистка', 'Естественное сияние', 'Гладкая текстура', 'Подходит чувствительной коже', 'Расслабляет'],
      ZH: ['深层清洁', '自然光泽', '光滑细腻', '敏感肌友好', '放松身心'],
      JA: ['深層クレンジング', '自然な輝き', 'なめらかな肌', '敏感肌に優しい', 'リラックス効果'],
      KO: ['깊은 클렌징', '자연스러운 광채', '매끄러운 질감', '민감성 피부 친화', '편안한 휴식'],
      FR: ['Peau nettoyée en profondeur', 'Éclat naturel', 'Texture lisse', 'Adapté peaux sensibles', 'Relaxant'],
      ES: ['Piel limpia profundamente', 'Brillo natural', 'Textura suave', 'Apto piel sensible', 'Relajante'],
    },
    process: {
      VI: [
        { step: 'Soi da', detail: 'Phân tích tình trạng da bằng máy chuyên dụng.' },
        { step: 'Làm sạch', detail: 'Tẩy trang + sữa rửa mặt phù hợp.' },
        { step: 'Tẩy tế bào chết', detail: 'Enzyme hoặc AHA nhẹ nhàng.' },
        { step: 'Massage', detail: 'Massage thư giãn 20 phút.' },
        { step: 'Mask + Dưỡng', detail: 'Mask phù hợp + dưỡng kết.' },
      ],
      EN: [
        { step: 'Skin diagnostics', detail: 'Skin analysis with dedicated equipment.' },
        { step: 'Cleansing', detail: 'Makeup remover + cleanser tailored to your skin.' },
        { step: 'Exfoliation', detail: 'Gentle enzyme or AHA exfoliation.' },
        { step: 'Massage', detail: '20-minute relaxing facial massage.' },
        { step: 'Mask + treatment', detail: 'Targeted mask plus finishing treatment.' },
      ],
      RU: [
        { step: 'Диагностика', detail: 'Анализ кожи на специальном оборудовании.' },
        { step: 'Очищение', detail: 'Демакияж + умывание под вашу кожу.' },
        { step: 'Эксфолиация', detail: 'Мягкий энзимный или AHA пилинг.' },
        { step: 'Массаж', detail: '20 минут расслабляющего массажа лица.' },
        { step: 'Маска + уход', detail: 'Целевая маска и финишный уход.' },
      ],
      ZH: [
        { step: '皮肤检测', detail: '专业仪器分析皮肤状况。' },
        { step: '清洁', detail: '卸妆 + 洁面，适合您的肌肤。' },
        { step: '去角质', detail: '温和酵素或 AHA 去角质。' },
        { step: '按摩', detail: '20 分钟放松面部按摩。' },
        { step: '面膜 + 护理', detail: '针对性面膜 + 收尾护理。' },
      ],
      JA: [
        { step: '肌診断', detail: '専用機器で肌分析。' },
        { step: 'クレンジング', detail: 'メイク落とし + 肌に合う洗顔。' },
        { step: '角質ケア', detail: '優しい酵素または AHA。' },
        { step: 'マッサージ', detail: '20 分のリラックスフェイシャル。' },
        { step: 'マスク + 仕上げ', detail: '目的別マスクと仕上げケア。' },
      ],
      KO: [
        { step: '피부 진단', detail: '전용 장비로 피부 분석.' },
        { step: '클렌징', detail: '메이크업 리무버 + 피부 맞춤 클렌저.' },
        { step: '각질 관리', detail: '부드러운 효소 또는 AHA.' },
        { step: '마사지', detail: '20분 편안한 페이셜 마사지.' },
        { step: '마스크 + 트리트먼트', detail: '맞춤 마스크와 마무리 트리트먼트.' },
      ],
      FR: [
        { step: 'Diagnostic peau', detail: 'Analyse avec un équipement dédié.' },
        { step: 'Nettoyage', detail: 'Démaquillant + nettoyant adaptés.' },
        { step: 'Exfoliation', detail: 'Enzyme douce ou AHA.' },
        { step: 'Massage', detail: '20 minutes de massage facial.' },
        { step: 'Masque + soin', detail: 'Masque ciblé et soin de finition.' },
      ],
      ES: [
        { step: 'Diagnóstico', detail: 'Análisis con equipo dedicado.' },
        { step: 'Limpieza', detail: 'Desmaquillante + limpiador adaptado.' },
        { step: 'Exfoliación', detail: 'Enzima suave o AHA.' },
        { step: 'Masaje', detail: '20 minutos de masaje facial.' },
        { step: 'Mascarilla + tratamiento', detail: 'Mascarilla específica y final.' },
      ],
    },
    aftercare: {
      VI: ['Tránh nắng 24h', 'Không tẩy da chết 3 ngày', 'Bôi kem chống nắng đầy đủ', 'Uống nhiều nước'],
      EN: ['Avoid sun for 24h', 'No exfoliants for 3 days', 'Always wear sunscreen', 'Drink plenty of water'],
      RU: ['Без солнца 24 часа', 'Без эксфолиантов 3 дня', 'Всегда SPF', 'Пейте много воды'],
      ZH: ['24 小时避光', '3 天不去角质', '始终防晒', '多喝水'],
      JA: ['24 時間日光を避ける', '3 日間角質ケア禁止', '常に日焼け止め', '水分補給'],
      KO: ['24시간 햇빛 피하기', '3일간 각질 관리 금지', '항상 자외선 차단제', '수분 섭취'],
      FR: ['Pas de soleil 24h', 'Pas d\'exfoliant 3 jours', 'Toujours du SPF', "Buvez beaucoup d'eau"],
      ES: ['Sin sol 24h', 'Sin exfoliantes 3 días', 'Siempre protector solar', 'Bebe mucha agua'],
    },
    faq: {
      VI: [{ q: 'Bao lâu làm 1 lần?', a: '2-4 tuần tùy tình trạng da.' }, { q: 'Da nhạy cảm có làm được?', a: 'Có, em sẽ chọn liệu trình phù hợp.' }],
      EN: [{ q: 'How often should I come?', a: 'Every 2–4 weeks depending on your skin.' }, { q: 'Is it safe for sensitive skin?', a: 'Yes — I customize the routine for your skin type.' }],
      RU: [{ q: 'Как часто приходить?', a: 'Каждые 2-4 недели в зависимости от кожи.' }, { q: 'Безопасно для чувствительной кожи?', a: 'Да — я подберу под ваш тип.' }],
      ZH: [{ q: '多久做一次？', a: '根据肌肤状况每 2-4 周一次。' }, { q: '敏感肌可以吗？', a: '可以，我会根据您的肤质定制。' }],
      JA: [{ q: '頻度は？', a: '肌の状態により 2〜4 週間ごと。' }, { q: '敏感肌でも大丈夫？', a: 'はい、肌タイプに合わせます。' }],
      KO: [{ q: '얼마나 자주 받아야 하나요?', a: '피부 상태에 따라 2-4주마다.' }, { q: '민감성 피부도 괜찮나요?', a: '네, 피부 타입에 맞게 조정합니다.' }],
      FR: [{ q: 'À quelle fréquence ?', a: 'Toutes les 2-4 semaines selon votre peau.' }, { q: 'Apte aux peaux sensibles ?', a: 'Oui — je personnalise selon votre type.' }],
      ES: [{ q: '¿Cada cuánto venir?', a: 'Cada 2-4 semanas según tu piel.' }, { q: '¿Apto piel sensible?', a: 'Sí — personalizo según tu tipo de piel.' }],
    },
  },
];

export function pickServiceLang<T>(field: Record<Lang, T>, lang: Lang): T {
  return field[lang] ?? field.EN;
}

export function getServiceBySlug(slug: string): ServiceDetail | undefined {
  return SERVICE_DETAILS.find((s) => s.slug === slug);
}

// Map service detail page slug → booking form dropdown key
export const SLUG_TO_BOOKING_KEY: Record<string, 'microblading' | 'lip' | 'eyeliner' | 'lash' | 'nail' | 'skin'> = {
  'microblading': 'microblading',
  'lip-blush': 'lip',
  'eyeliner': 'eyeliner',
  'noi-mi': 'lash',
  'nail-art': 'nail',
  'cham-soc-da': 'skin',
};
